{
    "id": "problem_27",
    "description": "\n\nWhen attempting to access a numpy array, a IndexError is thrown due to the index being out of range. The index is too large and is beyond the size of the numpy array.",
    "code": "import numpy as np\n\narr = np.array([1,2,3,4,5])\n\nprint(arr[10])",
    "tags": [
        "IndexError",
        "numpy",
        "Easy"
    ]
}