{
    "id": "problem_160",
    "description": "\n\nProblem Description: When attempting to calculate the sum of two numbers, a TypeError is thrown indicating that an unsupported type of math is being used.",
    "output": "Traceback (most recent call last):\n  File \"<stdin>\", line 9, in <module>\nIndentationError: expected an indented block",
    "tags": [
        "TypeError",
        "math",
        "Medium"
    ]
}